### ISSUE TITLE
does the proportion sampled affect ghost/self-recruitment rates?

### ISSUE THREAD

**Issue by katcatalano** [katcatalano/migest#1]
From clownfish meeting today. It looks like no. Check out the figure [here](https://github.com/katcatalano/migest/blob/master/20190612_1340loci/results/prop_samp_SR.png) showing how well we sampled a site doesn't have a clear association with estimates of self-recruitment.
The figure [here](https://github.com/katcatalano/migest/blob/master/20190612_1340loci/results/prop_samp_ghost.png) shows the same relationship with outside sources of recruits.

@agdedrick @mstuart1 @mpinsky , please chime in here with any more thoughts/suggestions! It is really striking that there are very few intermediate values (see [here](https://github.com/katcatalano/migest/blob/master/20190612_1340loci/results/annual_SR_ghost.png) for a plot of point estimates with the wide confidence intervals.)

**Comment by mpinsky** [comment]
Super helpful plots!

The SR vs. proportion sampled plot is interesting. It looks like under some
conditions there is a relationship (the striking line of points heading
down and right, and the other line heading up and right). Not sure what
those conditions would be.
